(function() {

	var _;

	var utils = require('./utils');


	var TypesService = function() {
	};


	TypesService.prototype.completeTypeDefinition = function(def, ctor) {
		def.ctor = ctor;
		if (!def.schema) {
			def.schema = {};
		}
		if (!def.schema.properties) {
			def.schema.properties = {};
		}
		if (!def.schema.required) {
			def.schema.required = [];
		}
		if (def.autoGenerated) {
			for (var k in def.autoGenerated) {
				def.schema.properties[k] = {
					type: 'integer'
				};
				def.schema.required.push(k);
			}
		}
		return def;
	};


	TypesService.prototype.resolveReferences = function*() {
		var def, name;
		for (name in TypesService.typeCache) {
			def = TypesService.typeCache[name];
			_ = yield* this.resolveReferencesInDef(def);
		}
	};


	TypesService.prototype.resolveReferencesInDef = function*(def) {
		var self = this;

		var fn = function*(val, prop) {
			var subTypeDef;
			if (val.type === 'object') {
				if (val.properties) {
					subTypeDef = {
						name: "<anonymous>",
						schema: {
							type: val.type,
							properties: val.properties,
							required: val.required
						}
					};
					prop.typeDefinition = subTypeDef;
					return yield* self.resolveReferencesInDef(subTypeDef);
				}
			} else if (val.$ref) {
				prop.typeDefinition = yield* self.getTypeDefinition(val.$ref);
				return prop.typeDefinition;
			}
		};

		for (var property in def.schema.properties) {
			var value = def.schema.properties[property];
			if (value.type === 'array') {
				_ = yield* fn(value.items, def.schema.properties[property].items);
			} else {
				_ = yield* fn(value, def.schema.properties[property]);
			}
		}
	};


	TypesService.prototype.buildTypeCache = function*() {
		var def, items, modelName;
		if (!TypesService.typeCache) {
			TypesService.typeCache = {};
			if (this.getCacheItems) {
				items = yield* this.getCacheItems();
				for (modelName in items) {
					def = items[modelName];
					TypesService.typeCache[modelName] = def;
				}
				return yield* this.resolveReferences();
			}
		}
	};


	TypesService.prototype.getTypeDefinitions = function() {
		if (!TypesService.typeCache) {
			throw new Error("TypesService was not initialized before calling getTypeDefinitions()");
		}
		return TypesService.typeCache;
	};


	TypesService.prototype.getTypeDefinition = function*(name, dynamicResolutionContext) {
		var _ref, _ref1;
		if (!dynamicResolutionContext) {
			dynamicResolutionContext = {};
		}
		return (_ref = (_ref1 = TypesService.typeCache[name]) !== null ?
				_ref1 : dynamicResolutionContext[name]) !== null ?
				_ref : yield* this.resolveDynamicTypeDefinition(name, dynamicResolutionContext);
	};


	TypesService.prototype.init = function*(name) {
		throw new Error("init() must be overridden in derived class");
	};


	TypesService.prototype.resolveDynamicTypeDefinition = function*(name) {
		throw new Error("resolveDynamicTypeDefinition() method must be overridden in derived class");
	};


	module.exports = TypesService;

}).call(this);
